-- MySQL Script generated by MySQL Workbench
-- Sun Oct 15 09:50:25 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tra
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tra
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tra` DEFAULT CHARACTER SET utf8 ;
USE `tra` ;

-- -----------------------------------------------------
-- Table `tra`.`facebook_user_auth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tra`.`facebook_user_auth` ;

CREATE TABLE IF NOT EXISTS `tra`.`facebook_user_auth` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `access_token` VARCHAR(255) NOT NULL,
  `facebook_id` VARCHAR(255) NOT NULL,
  `expires_in` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `facebook_id_UNIQUE` (`facebook_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tra`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tra`.`users` ;

CREATE TABLE IF NOT EXISTS `tra`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` BLOB NULL,
  `facebook_auth_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `facebook_id_idx` (`facebook_auth_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `facebook_auth_id_UNIQUE` (`facebook_auth_id` ASC),
  CONSTRAINT `users_facebook_id`
    FOREIGN KEY (`facebook_auth_id`)
    REFERENCES `tra`.`facebook_user_auth` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tra`.`places`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tra`.`places` ;

CREATE TABLE IF NOT EXISTS `tra`.`places` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `google_place_id` VARCHAR(255) NULL,
  `place` JSON NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `place_UNIQUE` (`google_place_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tra`.`recommendations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tra`.`recommendations` ;

CREATE TABLE IF NOT EXISTS `tra`.`recommendations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `place_id` INT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `recommendations_places_id_idx` (`place_id` ASC),
  INDEX `recommendations_user_id_idx` (`user_id` ASC),
  UNIQUE INDEX `rec_composite_key` (`place_id` ASC, `user_id` ASC),
  CONSTRAINT `recommendations_places_id`
    FOREIGN KEY (`place_id`)
    REFERENCES `tra`.`places` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `recommendations_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `tra`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
