-- MySQL Script generated by MySQL Workbench
-- Sun Jun 25 12:51:42 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tra
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tra
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tra` DEFAULT CHARACTER SET utf8 ;
USE `tra` ;

-- -----------------------------------------------------
-- Table `tra`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tra`.`users` ;

CREATE TABLE IF NOT EXISTS `tra`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` BLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tra`.`lists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tra`.`lists` ;

CREATE TABLE IF NOT EXISTS `tra`.`lists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `data` JSON NULL,
  `name` VARCHAR(90) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `tra`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tra`.`recommended_lists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tra`.`recommended_lists` ;

CREATE TABLE IF NOT EXISTS `tra`.`recommended_lists` (
  `id` INT NOT NULL,
  `user_id` INT NULL,
  `recommender_id` INT NULL,
  `data` JSON NULL,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `recommender_id_idx` (`recommender_id` ASC),
  CONSTRAINT `recommended_lists_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `tra`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `recommender_id`
    FOREIGN KEY (`recommender_id`)
    REFERENCES `tra`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
