version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/root/tra

    steps:
      - checkout
      - setup_remote_docker

      # install aws cli
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get install -y python3-pip
            sudo pip3 install awscli

      # build docker image
      - run:
          name: Build tra Docker image
          command: |
            docker build -t tra -f ./docker/Dockerfile .

      # run tests
      - run:
          name: run tests
          command: echo "no tests! yet."

      # deploy to AWS ECR
      - deploy:
          name: tag and push built image to ECR
          command: |
           login="$(aws ecr get-login --region us-east-2 --no-include-email)"
            ${login}

            # push every build
            docker tag tra "${ECR_ENDPOINT}/tra:${CIRCLE_SHA1}"
            docker push "${ECR_ENDPOINT}/tra:${CIRCLE_SHA1}"

            # if on master, also tag as prod and push
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag tra "${ECR_ENDPOINT}/tra:production"
              docker push "${ECR_ENDPOINT}/tra:production"
            fi
