#!/bin/bash

export NODE_PATH=./:./node_modules:./lib:$NODE_PATH

if [[ -z $NODE_ENV ]]; then
    export NODE_ENV="production"
fi

if [[ -z $S3_URL ]]; then
  export S3_URL="s3://tra-main/production/secrets"
fi

# Redis Config
if [[ -z $REDIS_HOST ]]; then
    export REDIS_HOST="redis-001.vvq8dm.0001.usw2.cache.amazonaws.com"
fi

if [[ -z $REDIS_PORT ]]; then
    export REDIS_PORT="6379"
fi

if [[ -z $REDIS_PASS ]]; then
    export REDIS_PASS=""
fi

# MySQL Config
if [[ -z $MYSQL_HOST ]]; then
  export MYSQL_HOST="dev-db.ccbt0aqgfw1z.us-west-2.rds.amazonaws.com"
fi

if [[ -z $MYSQL_USER ]]; then
  export MYSQL_USER="tra-user"
fi

if [[ -z $MYSQL_PORT ]]; then
  export MYSQL_PORT="3306"
fi

if [[ -z $MYSQL_DB ]]; then
  export MYSQL_DB="tra"
fi

if [[ -z $MYSQL_CONN_LIMIT ]]; then
  export MYSQL_CONN_LIMIT="100"
fi
